### ISSUE TITLE
Some guidance on usage

### ISSUE THREAD

**Issue by callumparr** [josiegleeson/BamSlam#3]
Hey! nice paper. I wanted to use this script to provide summary statistics of my mapped reads as well and cite your paper. Looking through the Rscript I can see we need to supply the file-path to the BAM file and output directory but there is also an argument flag for type. I was wondering what this was for. 

Can we run simply by:

`Rscript in.bam out.directory` as in arguments are positional or are there flags?

**Comment by callumparr** [comment]
haha I am stupid I just put my glasses on and saw there is a usage section in the readme. Sorry to disturb.

**Comment by josiegleeson** [comment]
No worries Callum! Please let me know if you have any trouble running it.
